import React from 'react';
import PropTypes from 'prop-types';

/**
 * Math component for rendering LaTeX/AsciiMath expressions.
 *
 * Security note: mathMl and svg are generated by MathJax from math expressions,
 * not from arbitrary user HTML input. This matches the security level of the
 * original inline HTML rendering in the math extension.
 */
const Math = ({ mathMl = '', svg = '' }) => {
  return (
    <>
      <span className="sr-only" dangerouslySetInnerHTML={{ __html: mathMl }} />
      <span aria-hidden="true" dangerouslySetInnerHTML={{ __html: svg }} />
    </>
  );
};

Math.propTypes = {
  math: PropTypes.string,
  typed: PropTypes.oneOf(['latex', 'asciimath', 'nemeth']),
  latex: PropTypes.string,
  mathMl: PropTypes.string,
  svg: PropTypes.string,
  position: PropTypes.shape({ start: PropTypes.number, end: PropTypes.number }),
};

export default Math;
